const ROLES = {
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  DEALER: 'DEALER',
  CUSTOMER: 'CUSTOMER',
  GUEST: 'GUEST'
};

const PAYMENT_METHODS = {
  QR_SCAN: 'QR_SCAN',
  PAYMENT_GATEWAY: 'PAYMENT_GATEWAY',
  COD: 'COD'
};

const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  FAILED: 'FAILED'
};

const ORDER_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED'
};

module.exports = { ROLES, PAYMENT_METHODS, PAYMENT_STATUS, ORDER_STATUS };
